version: '3'

services:

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123Rating
    volumes:
      - ./db/create-rating-db.sql:/docker-entrypoint-initdb.d/create-rating-db.sql

  rating-app:
    image: lopesgabriel/rating-spring-test
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "80:8081"
    links: 
      - db
    depends_on: 
      - db
